title: Pirátská strana Plzeň
email: to@pirati.cz
description: Prosazujeme fungující moderní politiku založenou na využití technologií 21. století pro otevřenou demokratickou společnost.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://plzen.pirati.cz" # the base hostname & protocol for your site

markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
paginate_path: "/aktuality/:num/"
paginate: 11

exclude:
  - readme.md
  - Gemfile
  - Gemfile.lock
  - package.json
  - bower.json
  - gulpfile.js
  - node_modules
  - bower_components
  - vendor

sass:
    style: compressed

permalink: /:title.html
collections:
  people:
    output: true
    permalink: /lide/:path/
  projects:
    output: true
    permalink: https://forum.pirati.cz/viewforum.php?f=517

defaults:   # defaults values for collection scope
  -
    scope:
      path: "_people"
    values:
      layout: "page"
      rbar: "people, foto"
  -
    scope:
      path: "_teams"
    values:
      layout: "team"
      rbar: "team-summary, teams-toc"

calendar: https://calendar.google.com/calendar/embed?src=fstbrgjct7a7cvkidpp08bit48%40group.calendar.google.com&ctz=Europe%2FPrague
fb: https://www.facebook.com/pirati.plzen/
tw: PiratiPlzen
instagram: pirati.plzen
title-page:
  big:
    foto: /assets/img/miscellaneous/PiCentrum.jpg
    alt: Plzeňské Pirátské Centrum
    url: picentrum #nahraď url třeba https://www.youtube.com/embed/2MpUj-Aua48?&autoplay=1
  left-top:
    text: Kdo jsme?
    url: lide
    icon: fa fa-users
  right-top:
    text: Piráti ve sněmovně
    url: https://www.pirati.cz/snemovna/
    icon: fa fa-newspaper-o u-rotate-345
  left-bottom:
    text: Program
    url: program
    icon: fa map-signs
  right-bottom:
    text: Facebook
    url: https://www.facebook.com/pirati.plzen/
    icon: fa fa-bullhorn u-rotate-345

emptyArray: []
